name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'        # run only when a version tag is pushed (e.g. v1.2.3)

permissions:
  id-token: write      
  contents: read       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      # Optional: make sure the package’s __version__ matches the git tag
      - name: Check version matches Git tag
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"   # strip leading "v"
          PKG_VER=$(python -c "import importlib.metadata as m; print(m.version('uk-midas-client'))" || true)
          echo "Git tag:       $TAG"
          echo "Package ver:   $PKG_VER"
          if [ "$TAG" != "$PKG_VER" ]; then
            echo "::error ::Version mismatch – tag is $TAG but package is $PKG_VER"
            exit 1
          fi

      - name: Build distributions
        run: python -m build 

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1